version: '3'
services:
  app:
    links:
      - mysql
    build:
      context: . 
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - mysql  
    ports:
      - "8080:8080"
    environment: 
      GO_ENV: docker
      TZ: Asia/Tokyo
    volumes:
      - ./app:/go/github.com/s-moteki/go-todo/app
      - ./envfiles:/go/github.com/s-moteki/go-todo/envfiles
  mysql:
    image: mysql:5.7
    ports: 
      - "3306:3306"
    volumes:
        - "./docker/db/conf.d/mysql.conf:/etc/mysql/conf.d/my.cnf"
        - "./docker/db/initdb.d:/docker-entrypoint-initdb.d"
        - "./log/mysql:/var/log/mysql"  
        - "./docker/db/data:/var/lib/mysql"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    